### ISSUE TITLE
Maintainer customer development

### ISSUE THREAD

**Issue by ftdgoodluck** [NEAR-DevHub/devbot#3]
Run a series of interviews across our first maintainers. Need to have the following:

- Overall impression on the project (interesting / not interesting)
- Feedback on chosen interaction approach
- Soft commits to participate in MVP
```[tasklist]
### Tasks
- [ ] Get a list of first cohort on interested projects to be whitelisted
- [ ] gather feedback on the approach and implement deal-breaking changes
- [ ] Get a list of soft commits
```

**Comment by ftdgoodluck** [comment]
Agreed to skip this (at least for now) since we'll start from friendly repos and core contributors of these repos so we don't need to work specifically on attracting contributors. All friendly repos would be listed in #4
